# Generated by Django 4.2.5 on 2023-11-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="items",
        ),
    ]
