# Generated by Django 4.2.5 on 2023-11-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_remove_vendor_items"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Delay",
            new_name="DelayQueue",
        ),
    ]
